<a href="https://colab.research.google.com/github/shyamalkar/Data_science_assignment_task_1/blob/main/titanic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
from google.colab import files
upload = files.upload()

Saving titanic (1).csv to titanic (1) (2).csv

In [39]:
import pandas as pd

df = pd.read_csv('titanic (1).csv')

df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [40]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

*`Import and Explore the Dataset`*

First, we load the necessary libraries and the Titanic dataset . For this example, We use the Version provided directly by the Seaborn library .

In [41]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


# Explore the dataset
print('See the first 5 row: \n\t', df.head())
print('All info see here\n\t', df.info())
print('Usage for null and missing value are present here\n\t', df.isnull().sum())

See the first 5 row:
	    PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
All info see here
	 None
Usage for null and missing value are present here
	 PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

***`Data Cleaning and Preprocessing`***

``We need to handle missing values and encode categorical variables as requested.``

In [42]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [43]:

# Create a copy so we don't modify the original 'df' unexpectedly
df_cleaned = df.copy()
# Handle missing values
df_cleaned['Age'] = df_cleaned['Age'].fillna(df_cleaned['Age'].median())
df_cleaned['Embarked'] = df_cleaned['Embarked'].fillna(df_cleaned['Embarked'].mode()[0])

# Encode Categorical variables
df_cleaned['Sex'] = df_cleaned['Sex'].map({'male': 0, 'female': 1})

# Convert Embarked to numbers (S=0, C=1, Q=2)
df_cleaned['Embarked'] = df_cleaned['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

# Drop ONLY the columns that are text-heavy or IDs
df_cleaned.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], inplace=True)

print("Data cleaning successful!")
df_cleaned.head()

Data cleaning successful!

   Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    0  22.0      1      0   7.2500         0
1         1       1    1  38.0      1      0  71.2833         1
2         1       3    1  26.0      0      0   7.9250         0
3         1       1    1  35.0      1      0  53.1000         0
4         0       3    0  35.0      0      0   8.0500         0

In [44]:
X = df_cleaned[['Pclass', 'Sex', 'Age', 'Parch', 'Fare', 'Embarked']]
X

     Pclass  Sex   Age  Parch     Fare  Embarked
0         3    0  22.0      0   7.2500         0
1         1    1  38.0      0  71.2833         1
2         3    1  26.0      0   7.9250         0
3         1    1  35.0      0  53.1000         0
4         3    0  35.0      0   8.0500         0
..      ...  ...   ...    ...      ...       ...
886       2    0  27.0      0  13.0000         0
887       1    1  19.0      0  30.0000         0
888       3    1  28.0      2  23.4500         0
889       1    0  26.0      0  30.0000         1
890       3    0  32.0      0   7.7500         2

[891 rows x 6 columns]

In [45]:
# CHANGE 'df' to 'df_cleaned' HERE
X = df_cleaned[['Pclass', 'Sex', 'Age', 'Parch', 'Fare', 'Embarked']]
y = df_cleaned['Survived']

# The rest of your code will now work because 'Sex' is 0/1 and 'Embarked' is 0/1/2
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

y_pred = nb_model.predict(X_test)

# Final Metrics
print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print(classification_report(y_test, y_pred))

Accuracy: 0.75
              precision    recall  f1-score   support

           0       0.79      0.79      0.79       105
           1       0.70      0.70      0.70        74

    accuracy                           0.75       179
   macro avg       0.75      0.75      0.75       179
weighted avg       0.75      0.75      0.75       179

# ***`Split Dataset and Implement Naive Bayes`***

``Split Dataset and Implement Naive Bayes
Next, we split the data into training and testing sets and apply the Gaussian Naive Bayes classifier``

In [51]:
# Change 'df' to 'df_cleaned'
X = df_cleaned[['Pclass', 'Sex', 'Age', 'Parch', 'Fare', 'Embarked']]
y = df_cleaned['Survived']

# Split the dataset (80% training, 20% testing)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Implement Naive Bayes Classifier
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

# Make predictions
y_pred = nb_model.predict(X_test)

***`Evoluation and Analysis`***

In [52]:
# Metrics
print(f"Accuracy Score: {accuracy_score(y_test, y_pred):.2f}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy Score: 0.75

Confusion Matrix:
[[83 22]
 [22 52]]

Classification Report:
              precision    recall  f1-score   support

           0       0.79      0.79      0.79       105
           1       0.70      0.70      0.70        74

    accuracy                           0.75       179
   macro avg       0.75      0.75      0.75       179
weighted avg       0.75      0.75      0.75       179